
kws = {
    "struct": "EBI_KW_STRUCT",
    "class": "EBI_KW_CLASS",
    "def": "EBI_KW_DEF",
    "let": "EBI_KW_LET",
    "return": "EBI_KW_RETURN",
}

def kw_hash(s):
    h = 0
    for c in s:
        h = ((h ^ ord(c)) * 0x9e3779b9) & 0xffff_ffff
    return h

for log_num in range(30):
    num = 1 << log_num
    for shift in range(30):
        vals = [None] * num
        for kw, enum in kws.items():
            h = kw_hash(kw)
            ix = (h >> shift) % len(vals)
            if vals[ix]: break
            vals[ix] = h, kw, enum
        else:
            print("// Generated by misc/make_kw_map.py")
            print(f"static const uint32_t ebi_kw_shift = {shift};")
            print("static const ebi_kw_mapping ebi_kw_map[] = {")
            for val in vals:
                if val:
                    h, kw, enum = val
                    print(f"\n\t{{ 0x{h:08x}, {len(kw)}, \"{kw}\", {enum} }},", end="")
                else:
                    print(" { 0 },", end="")
            print("\n};")
            exit(0)
exit(1)
